apiVersion: v1
kind: ConfigMap
metadata:
  name: services-config
  namespace: chat-platform
data:
  NODE_ENV: production
  PORT: "3000"
  POSTGRES_HOST: postgres-svc
  POSTGRES_PORT: "5432"
  REDIS_HOST: redis-svc
  REDIS_PORT: "6379"
