apiVersion: v1
kind: Service
metadata:
  name: presence-service-svc
  namespace: chat-platform
spec:
  type: ClusterIP
  selector:
    app: presence-service
  ports:
    - port: 3000
      targetPort: 3000
